### ISSUE TITLE
Mismatched optimizer for Histology nuclei segmentation

### ISSUE THREAD

**Issue by ddayzzz** [med-air/HarmoFL#1]
Thank you for this great work. I have question that the optimizer mentioned in Histology nuclei segmentation is SGD is correct? I read the code [fed_train.py#L274](https://github.com/med-air/HarmoFL/blob/3e47d43cd41b993f7d535fa84daa970c4eb43939/federated/fed_train.py#L274) and found that Adam is used instead of SGD mentioned in the paper.

**Comment by MeiruiJiang** [comment]
Many thanks for your interest, we have checked the code, the optimizer for histology nuclei segmentation is the same as the prostate segmentation, should be Adam. Thanks for pointing out this, we will correct this typo in the paper accordingly.
