### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/prostate/ISBI/Case00.nii.gz'

### ISSUE THREAD

**Issue by xiaohongri** [med-air/HarmoFL#4]
when  run test.sh ,there is problem ,how to solve this?
FileNotFoundError: [Errno 2] No such file or directory: '../data/prostate/ISBI/Case00.nii.gz'

**Comment by MeiruiJiang** [comment]
Thanks for your interest in our work. Could you please provide more information? 
Here are some check steps:
1. Please make sure you have the data. (if not, please download via this link).
2. Please check the path. You can change to the absolute path to see if this error will be reproduced.

**Comment by ToughCookies2020** [comment]
I ran into the same problem. There are no ISBI and ISBI_1.5 files in the downloaded data set, but there are more BMC and RUNMC files. In addition, I hope that the author can open the code of plotting.

**Comment by MeiruiJiang** [comment]
> I ran into the same problem. There are no ISBI and ISBI_1.5 files in the downloaded data set, but there are more BMC and RUNMC files. In addition, I hope that the author can open the code of plotting.

It seems the original data source changed the file name. Please revise the folder name accordingly. Sorry for the inconvenience.

For the plotting, we refer to this repo for drawing the landscape (https://github.com/tomgoldstein/loss-landscape).

**Comment by xiaohongri** [comment]
Thanks for your reply, As you said,i have solved this problem, i hope there will be more in-depth exchanges in the future.

--------------原始邮件--------------
发件人："Meirui&nbsp;Jiang ***@***.***&gt;;
发送时间：2023年3月21日(星期二) 下午2:04
收件人："med-air/HarmoFL" ***@***.***&gt;;
抄送："肖宏日 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [med-air/HarmoFL] FileNotFoundError: [Errno 2] No such file or directory: '../data/prostate/ISBI/Case00.nii.gz' (Issue #4)
-----------------------------------

 

  
I ran into the same problem. There are no ISBI and ISBI_1.5 files in the downloaded data set, but there are more BMC and RUNMC files. In addition, I hope that the author can open the code of plotting.
  
It seems the original data source changed the file name. Please revise the folder name accordingly. Sorry for the inconvenience.
 
For the plotting, we refer to this repo for drawing the landscape (https://github.com/tomgoldstein/loss-landscape).

**Comment by cui-yc** [comment]
Why is it wrong for me to use data/prostate directly on this dataset? Does any additional processing need to be done？
